name: Publish to Crates.io

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags (v0.1.8, v1.0.0, etc.)

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to Crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-publish-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-publish-
    
    # Minimal smoke test - just verify it compiles and basic tests pass
    - name: Run smoke tests
      run: |
        cargo check --all-features
        cargo test --lib --bins --all-features
    
    # Verify the package can be built for publishing
    - name: Verify publish readiness
      run: cargo publish --dry-run --all-features
    
    # Publish to crates.io
    - name: Publish to crates.io
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    
    # Create GitHub release
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          README.md
          CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
